services:
  - type: web
    name: rest-api-db
    env: node
    healthCheckPath: /health
    plan: free
    buildCommand: "npm install"
    startCommand: "node rest-api-db.js"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://antonella:1234@cluster0.qxz4vxb.mongodb.net/Clima?retryWrites=true&w=majority&appName=Cluster0
      - key: REST_API_URL
        value: https://rest-api-db.onrender.com/temperatura_api

  - type: web
    name: webhook
    env: node
    healthCheckPath: /health
    plan: free
    buildCommand: "npm install"
    startCommand: "node webhook-server.js"
    envVars:
      - key: REST_API_URL
        value: https://rest-api-db.onrender.com/temperatura_api
      - key: WEBHOOK_URL
        value: https://webhook-k8gk.onrender.com/webhook

  - type: web
    name: ws-server
    env: node
    plan: free
    healthCheckPath: /health
    buildCommand: "npm install"
    startCommand: "node ws-server.js"
    envVars:
      - key: WEBHOOK_URL
        value: https://webhook-k8gk.onrender.com/webhook

  - type: web
    name: ws-client
    env: node
    healthCheckPath: /health
    plan: free
    buildCommand: "npm install"
    startCommand: "node ws-client.js"
    envVars:
      - key: WS_SERVER_URL
        value: wss://ws-server-pa1h.onrender.com
      - key: WEBHOOK_URL
        value: https://webhook-k8gk.onrender.com/webhook

  - type: web
    name: auth
    env: node
    healthCheckPath: /health
    plan: free
    buildCommand: "npm install"
    startCommand: "node auth.js"
    envVars:
      - key: JWT_SECRET
        value: miclavesupersegura
